name: basicflutter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^1.3.1
  scan: ^1.5.0
  google_place: ^0.4.3
  form_field_validator: ^1.1.0
  firebase_core: ^1.11.0
  google_sign_in: ^5.2.3
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.7
  webview_flutter: ^3.0.0
  ionicons: ^0.1.2
  font_awesome_flutter: ^9.2.0
  firebase_storage: ^10.2.7
  url_launcher: ^6.0.18
  flutter_local_notifications: ^9.4.0
  firebase_messaging: ^11.2.7
  barcode_scan2: ^4.2.0
  dropdown_button2: ^1.2.3

flutter_icons:
  android: true
  image_path: "image/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - image/
  fonts:
    - family: Prompt
      fonts:
        - asset: fonts/Prompt-Regular.ttf

flutter_native_splash:
  background_image: "assets/frampage.png"